// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3rnBo8VpEy1KLo2SjYxw6jcZ2mHpxXhs',
    appId: '1:481160676993:web:e88bdaf87722cd3e17ef80',
    messagingSenderId: '481160676993',
    projectId: 'fungi-97456',
    authDomain: 'fungi-97456.firebaseapp.com',
    storageBucket: 'fungi-97456.firebasestorage.app',
    measurementId: 'G-6VNPR93N2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFFMbNK5eKcZv3UAHow5ZB8kK8hF2XSs8',
    appId: '1:481160676993:android:7bfdf9c5fe0894f417ef80',
    messagingSenderId: '481160676993',
    projectId: 'fungi-97456',
    storageBucket: 'fungi-97456.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyLO4zXbx4vGdTFoOMLBJE_MDJHe92Das',
    appId: '1:481160676993:ios:d3eec6615c6b0eea17ef80',
    messagingSenderId: '481160676993',
    projectId: 'fungi-97456',
    storageBucket: 'fungi-97456.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyLO4zXbx4vGdTFoOMLBJE_MDJHe92Das',
    appId: '1:481160676993:ios:d3eec6615c6b0eea17ef80',
    messagingSenderId: '481160676993',
    projectId: 'fungi-97456',
    storageBucket: 'fungi-97456.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3rnBo8VpEy1KLo2SjYxw6jcZ2mHpxXhs',
    appId: '1:481160676993:web:35325add9e276d1817ef80',
    messagingSenderId: '481160676993',
    projectId: 'fungi-97456',
    authDomain: 'fungi-97456.firebaseapp.com',
    storageBucket: 'fungi-97456.firebasestorage.app',
    measurementId: 'G-Q860RVC65Q',
  );
}
